#!/usr/bin/env python
import rospy

from vigir_ocs_behavior_manager.vigir_ocs_behavior_manager import BehaviorManager

if __name__ == '__main__':
    rospy.init_node('vigir_ocs_behavior_manager')
    be_input = BehaviorManager()

    # Wait for ctrl-c to stop the application
    rospy.spin()
